---
version: 2.1

parameters:
  hc-product:
    type: string
    default: "dummy"
  hc-version:
    type: string
    default: "0.0.1"
  hc-package-iteration:
    type: string
    default: "1"

references:
  docker-images:
    artifactory: &ARTIFACTORY_DOCKER_IMAGE productdelivery-docker-release-local.artifactory.hashicorp.engineering/artifactory-repo-tool:0.1.16
    fedora: &FEDORA_DOCKER_IMAGE "fedora@sha256:ee55117b3058f2f12961184fae4b9c392586e400487626c6bd0d15b4eae94ecc"
    ubuntu: &UBUNTU_DOCKER_IMAGE "circleci/buildpack-deps:bionic"

environment: &ENVIRONMENT
    HC_PRODUCT: << pipeline.parameters.hc-product >>
    HC_VERSION: << pipeline.parameters.hc-version >>
    HC_PACKAGE_ITERATION: << pipeline.parameters.hc-package-iteration >>
    IMAGE_RPM_SYSTEM: *FEDORA_DOCKER_IMAGE
    IMAGE_APT_SYSTEM: *UBUNTU_DOCKER_IMAGE

jobs:
  package:
    docker:
      - image: *FEDORA_DOCKER_IMAGE
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - run:
          name: Install make
          command: sudo dnf -y install make
      - run:
          name: Create linux packages
          command: make package

workflows:
  version: 2
  packaging:
    jobs:
      - package:
          filters:
            branches:
              only: dev
