---
version: 2.1

parameters:
  hc-product:
    type: string
    default: "vault_selinux"
  hc-version:
    type: string
    default: "0.1.1"
  hc-package-iteration:
    type: string
    default: "1"

references:
  docker-images:
    artifactory: &ARTIFACTORY_DOCKER_IMAGE productdelivery-docker-release-local.artifactory.hashicorp.engineering/artifactory-repo-tool:0.1.16
    fedora: &FEDORA_DOCKER_IMAGE "fedora@sha256:ee55117b3058f2f12961184fae4b9c392586e400487626c6bd0d15b4eae94ecc"
    ubuntu: &UBUNTU_DOCKER_IMAGE "circleci/buildpack-deps:bionic"
    centos: &CENTOS_DOCKER_IMAGE "centos:8"

environment: &ENVIRONMENT
    HC_PRODUCT: << pipeline.parameters.hc-product >>
    HC_VERSION: << pipeline.parameters.hc-version >>
    HC_PACKAGE_ITERATION: << pipeline.parameters.hc-package-iteration >>
    IMAGE_RPM_SYSTEM: *FEDORA_DOCKER_IMAGE
    IMAGE_CENTOS_SYSTEM: *CENTOS_DOCKER_IMAGE
    IMAGE_APT_SYSTEM: *UBUNTU_DOCKER_IMAGE

jobs:
  package:
    parameters:
      host-image:
        type: string
    docker:
      - image: << parameters.host-image >>
    environment:
      <<: *ENVIRONMENT
    steps:
      - checkout
      - when:
          condition:
            equal: [ << parameters.host-image >>, *FEDORA_DOCKER_IMAGE ]
          steps:
            - run: dnf -y install make
      - when:
          condition:
            equal: [ << parameters.host-image >>, *CENTOS_DOCKER_IMAGE ]
          steps:
            - run: yum -y install make
      - run:
          name: Create linux packages
          command: make package
      - run:
          name: Copy rpms to /tmp/circle-artifacts
          command: mkdir -p /tmp/circle-artifacts && cp products/<< pipeline.parameters.hc-product >>/*.rpm /tmp/circle-artifacts
      - store_artifacts:
          path: /tmp/circle-artifacts
      - persist_to_workspace:
          root: .
          paths:
            - products/<< pipeline.parameters.hc-product >>/*.rpm
      - when:
          condition:
            equal: [ << parameters.host-image >>, *CENTOS_DOCKER_IMAGE ]
          steps:
            - persist_to_workspace:
                root: .
                paths:
                  - products/<< pipeline.parameters.hc-product >>/ci
  validate-packages:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      <<: *ENVIRONMENT
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Validate packages
          command: |
            ./products/<< pipeline.parameters.hc-product >>/ci/validate.sh

workflows:
  version: 2
  packaging:
    jobs:
      - package:
          matrix:
            parameters:
              host-image: [*FEDORA_DOCKER_IMAGE, *CENTOS_DOCKER_IMAGE]
          filters:
            branches:
              only: dev
      - validate-packages:
          requires:
            - package
